const Pokemones = [
  {
    nombre: "Bulbasaur",
    numero: `001`,
    color: "#74cb48",
    elemento: ["Gras", "Poison"],
    peso: 6.9,
    altura: 0.7,
    movimiento: "Chlorophyll",
    movimientoSecundario: "OverGrow",
    descripcion:
      "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    stats: {
      hp: `045`,
      atk: `049`,
      def: `049`,
      satk: `065`,
      sdef: `065`,
      spd: `045`,
    },
  },
  {
    nombre: "Charmander",
    numero: `004`,
    color: "#f57d31",
    elemento: ["Fire"],
    peso: 8.5,
    altura: 0.6,
    movimiento: "Mega-Punch",
    movimientoSecundario: "Fire-Punch",
    descripcion:
      "It has a preference for hot things. when it rains, steam is said to spout from the tip of its tail.",
    stats: {
      hp: `039`,
      atk: `052`,
      def: `043`,
      satk: `060`,
      sdef: `050`,
      spd: `065`,
    },
  },
  {
    nombre: "Squirtle",
    numero: `007`,
    color: "#6493eb",
    elemento: ["Water"],
    peso: 9.0,
    altura: 0.5,
    movimiento: "Torrent",
    movimientoSecundario: "Rain-Dish",
    descripcion:
      "When ot retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
      hp: `044`,
      atk: `048`,
      def: `065`,
      satk: `050`,
      sdef: `064`,
      spd: `043`,
    },
  },
  {
    nombre: "Butterfree",
    numero: `012`,
    color: "#a7b723",
    elemento: ["Bug", "Flying"],
    peso: 32.0,
    altura: 1.1,
    movimiento: "Compound-Eyes",
    movimientoSecundario: "Tinted-Lens",
    descripcion:
      "In battle, it flaps its wings at great speed to release highly toxic dust into the air.",
    stats: {
      hp: `060`,
      atk: `045`,
      def: `050`,
      satk: `090`,
      sdef: `080`,
      spd: `070`,
    },
  },
  {
    nombre: "Pikachu",
    numero: `025`,
    color: "#f9cf30",
    elemento: ["Electric"],
    peso: 6.0,
    altura: 0.4,
    movimiento: "Pay-Day",
    movimientoSecundario: "",
    descripcion:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    stats: { hp: 35, atk: 55, def: 40, satk: 50, sdef: 50, spd: 90 },
  },
  {
    nombre: "Gastly",
    numero: `092`,
    color: "#70559b",
    elemento: ["Ghost", "Type"],
    peso: 0.1,
    altura: 1.3,
    movimiento: "Levitate",
    movimientoSecundario: "",
    descripcion:
      "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    stats: {
      hp: `030`,
      atk: `035`,
      def: `030`,
      satk: 100,
      sdef: `035`,
      spd: `080`,
    },
  },
  {
    nombre: "Ditto",
    numero: 132,
    color: "#aaa67f",
    elemento: ["Normal"],
    peso: 4.0,
    altura: 0.3,
    movimiento: "Limber",
    movimientoSecundario: "Imposter",
    descripcion:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    stats: {
      hp: `048`,
      atk: `048`,
      def: `048`,
      satk: `048`,
      sdef: `048`,
      spd: `048`,
    },
  },
  {
    nombre: "Mew",
    numero: 152,
    color: "#fb5584",
    elemento: ["Psychic"],
    peso: 4.0,
    altura: 0.4,
    movimiento: "Synchronize",
    movimientoSecundario: "",
    descripcion:
      "When viewed through a microscope, this Pokémon's short, fine, delicate hair can be seen.",
    stats: { hp: 100, atk: 100, def: 100, satk: 100, sdef: 100, spd: 100 },
  },
  {
    nombre: "Aron",
    numero: 304,
    color: "#b7b9d0",
    elemento: ["Steel", "Rock"],
    peso: 60,
    altura: 0.4,
    movimiento: "sturdy",
    movimientoSecundario: "Rock-Head",
    descripcion:
      "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    stats: {
      hp: `050`,
      atk: `070`,
      def: 100,
      satk: `040`,
      sdef: `040`,
      spd: `030`,
    },
  },
];

export default Pokemones;
